# Generated by Django 5.0.6 on 2024-06-23 10:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DjangoNinjas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(max_length=50)),
                ('api_key', models.CharField(max_length=100)),
                ('secret_key', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='BalancesData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset', models.CharField(max_length=50)),
                ('free', models.DecimalField(decimal_places=5, max_digits=20)),
                ('locked', models.DecimalField(decimal_places=5, max_digits=20)),
                ('Client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='binance_app.djangoninjas')),
            ],
            options={
                'verbose_name_plural': 'BalancesData',
            },
        ),
    ]
