# Generated by Django 5.0.6 on 2024-06-23 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('binance_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BalanceData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset', models.CharField(max_length=50)),
                ('free', models.DecimalField(decimal_places=5, max_digits=20)),
                ('locked', models.DecimalField(decimal_places=5, max_digits=20)),
                ('wallet', models.CharField(max_length=50)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='binance_app.djangoninjas')),
            ],
            options={
                'verbose_name_plural': 'BalancesData',
            },
        ),
        migrations.DeleteModel(
            name='BalancesData',
        ),
    ]
